# -*- coding: utf-8 -*-
"""DATA SCIENCE .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLeyyu9G7FS4F_YlWTuxQ8JhCoF-V1w5
"""

!pip install -q kaggle

!kaggle datasets download -d reihanenamdari/breast-cancer

!unzip breast-cancer.zip

!unzip breast-cancer.zip

!ls

import pandas as pd

df = pd.read_csv('Breast_Cancer.csv')



import pandas as pd

df = pd.read_csv('Breast_Cancer.csv')

import os

for root, dirs, files in os.walk('.'):
    for file in files:
        print(os.path.join(root, file))

!kaggle datasets download -d reihanenamdari/breast-cancer

!unzip -o breast-cancer.zip

import pandas as pd

df = pd.read_csv("Breast_Cancer.csv")

print(df.head())
print(df.shape)
print(df.columns)

# Count duplicate rows
duplicates = df.duplicated().sum()

print("Number of duplicate rows:", duplicates)

import pandas as pd

# Load dataset
df = pd.read_csv("Breast_Cancer.csv")

# Head
print("----- HEAD -----")
print(df.head())

# Tail
print("\n----- TAIL -----")
print(df.tail())

# Length
print("\n----- LENGTH -----")
print(len(df))

# Shape
print("\n----- SHAPE -----")
print(df.shape)

# Info
print("\n----- INFO -----")
print(df.info())

# Describe
print("\n----- DESCRIBE -----")
print(df.describe())

# Data Types
print("\n----- DTYPES -----")
print(df.dtypes)

# Columns
print("\n----- COLUMNS -----")
print(df.columns)

# Duplicate Rows
print("\n----- DUPLICATES -----")
print("Number of duplicate rows:", df.duplicated().sum())

# Missing Values
print("\n----- MISSING VALUES -----")
print(df.isnull().sum())

print(df[df.duplicated()])

df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)



df.head()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load dataset
df = pd.read_csv("data.csv")

# Remove duplicate rows
df = df.drop_duplicates()

# Handle missing values
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

# Fill missing numerical values with mean
num_imputer = SimpleImputer(strategy='mean')
df[num_cols] = num_imputer.fit_transform(df[num_cols])

# Fill missing categorical values with most frequent value
cat_imputer = SimpleImputer(strategy='most_frequent')
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

# Encode categorical columns
encoder = LabelEncoder()
for col in cat_cols:
    df[col] = encoder.fit_transform(df[col])

# Separate features and target
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Scale features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

import pandas as pd

df = pd.read_csv("Breast_Cancer.csv")

!ls

df = pd.read_csv("Breast_Cancer.csv")

import os
print(os.listdir())

df = pd.read_csv("Breast_Cancer.csv")