# -*- coding: utf-8 -*-
"""TRAINING PYTHON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UrNpNVLkjQ9Z4UuOWzw_6OfbtVK3aW13
"""

num = int(input("Enter a number: "))

if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")



year = int(input("Enter year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print("Leap Year")
else:
    print("Not a Leap Year")

num = int(input("Enter a number: "))

if num % 2 == 0:
    print("Even")
else:
    print("Odd")

str1 = input("Enter first word: ")
str2 = input("Enter second word: ")

if sorted(str1) == sorted(str2):
    print("Anagram")
else:
    print("Not Anagram")

for i in range(1, 7):
    for j in range(1, i + 1):
        print(j, end="")
    print()

for i in range(5, 0, -1):
    for j in range(i):
        print("*", end="")
    print()

rows = 3

for i in range(1, rows + 1):
    print(" " * (rows - i) + "*" * (2 * i - 1))

for i in range(rows - 1, 0, -1):
    print(" " * (rows - i) + "*" * (2 * i - 1))

rows = 5

for i in range(1, rows + 1):
    print(" " * (rows - i) + "*" * (2 * i - 1))

str1 = input("Enter first word: ")
str2 = input("Enter second word: ")

if len(str1) != len(str2):
    print("Not Anagram")
else:
    count = 0
    for i in str1:
        if i in str2:
            count += 1

    if count == len(str1):
        print("Anagram")
    else:
        print("Not Anagram")

num = int(input("Enter a number: "))

if num > 0 and (num & (num - 1)) == 0:
    print("Power of 2")
else:
    print("Not Power of 2")

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

largest = max(a, b, c)

print("Largest number is:", largest)

s = input("Enter a string: ")

max_length = 0
start = 0
used = {}

for i in range(len(s)):
    if s[i] in used and used[s[i]] >= start:
        start = used[s[i]] + 1

    used[s[i]] = i
    max_length = max(max_length, i - start + 1)

print("Length of longest substring:", max_length)

n = int(input())
arr = list(map(int, input().split()))

x = 1

while x in arr:
    x += 1

print(x)

s = input("Enter a string: ")

longest = ""

for i in range(len(s)):

    l = r = i
    while l >= 0 and r < len(s) and s[l] == s[r]:
        if (r - l + 1) > len(longest):
            longest = s[l:r+1]
        l -= 1
        r += 1

    l = i
    r = i + 1
    while l >= 0 and r < len(s) and s[l] == s[r]:
        if (r - l + 1) > len(longest):
            longest = s[l:r+1]
        l -= 1
        r += 1

print("Longest Palindromic Substring:", longest)
print("Length:", len(longest))

s1 = input()
s2 = input()

count = 0

if len(s1) == len(s2):

    for i in range(len(s1)):
        if s1[i] != s2[i]:
            count += 1

    if count == 1:
        print("Yes")
    else:
        print("No")

else:
    print("No")



s = input()

v = "aeiouAEIOU"
a = []

for ch in s:
    if ch in v:
        a.append(ch)

a.reverse()

result = ""

for ch in s:
    if ch in v:
        result += a.pop(0)
    else:
        result += ch

print(result)

class father:
#inheritance
    def bike(self):
        print("father has bike")
class son(father):

    def cycle(self):
        print("son has cycle")
obj = son()
obj. cycle()

"""BREAK STATEMENT
THE BREAK STATEMENT IS USED TO TERMINATE THE LOOP IMMEDIATELY WHEN A CONDITION IS MET.
SYNTAX
for/while condition:
  if condition:
   break
   

CONTINUE STATEMENT
TO SKIP THE CURRENT ITERATION AND MOVE TO THE NEXT ITERATION.
SYNTAX
for/while condition:
if condition:
continue

PASS STATEMENT
IS A NULL OPERATION
IS USED AS A PLACEHOLDER WHERE CODE IS REQUIRED SYNTACTICALLY.
SYNTAX
for/while condition:
pass
"""

n = int(input())

rev = int(str(n)[::-1])

print(rev)

arr = list(map(int, input().split()))

for n in arr:
    if n % 2 == 0:
        print(-n, end=" ")
    else:
        print(n, end=" ")

n = int(input())

square1 = n * n
reverse1 = int(str(square1)[::-1])

reverse_num = int(str(n)[::-1])
square2 = reverse_num * reverse_num

print(reverse1)
print(square2)

n = input()

for i in range(len(n)):
    r = n[i:] + n[:i]
    print(r)

